spring.application.name=college-erp-backend
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
jwt.secret-key=${JWT_SECRET_KEY}
jwt.expiration-time=${JWT_EXPIRATION_TIME}